sudo: enabled
language: bash

env:
  global:
    - DISTRO=ubuntu:16.04
    - BUILD_DIR=/build
    - PACKAGES="ruby2.5 ruby2.5-dev ruby-switch bundler libglib2.0-dev zlib1g-dev git sudo postgresql-9.5 postgresql-server-dev-9.5 libvips-dev libvips-tools ffmpeg mkvtoolnix"
    - DATABASE_URL="postgresql:///danbooru_test?template=template0"

services:
  - docker

before_install:
  - docker run -d --name test-container -v $(pwd):$BUILD_DIR $DISTRO sleep 1d

install:
  - docker exec -t test-container bash -c "
    cd $BUILD_DIR;
    apt-add-repository ppa:brightbox/ruby-ng;
    apt-get update;
    apt-get install -y $PACKAGES;

    service postgresql start;
    sudo -u postgres createuser --echo --superuser root;
    createdb --echo --template=template0 danbooru_test;

    cp script/install/danbooru_local_config.rb.templ config/danbooru_local_config.rb;
    ruby-switch --set ruby2.5

    git clone https://github.com/r888888888/test_parser.git $BUILD_DIR/test_parser;
    cd $BUILD_DIR/test_parser;
    make install;
    "

script:
  - docker exec -t test-container bash -c "
    cd $BUILD_DIR;
    bundle install && bundle exec rake"